hypertrace/document-store

document-store/build.gradle.kts, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoDatastore.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoCollectionTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoDatastoreTest.java
https://github.com/hypertrace/hypertrace/issues/120
=> Upgrading Mongo java driver from 3.12 to 4.1.1

document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresDatastore.java
still need to refactor the methods which are **bulkUpsertAndReturnOlderDocuments** and **search** in **PostgresCollection.class**
facing issues describe in [https://stackoverflow.com/questions/1870022/java-iterator-backed-by-a-resultset](url)
=> Bug fix preapared statement close

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/Query.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/test/java/org/hypertrace/core/documentstore/QueryTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoCollectionTest.java
Adds support for projections in Mongo
Added Unit and Integration Tests
=> feat: support projections in mongo

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/postgres/PostgresDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/PostgresCollectionTest.java
Implement NEQ filter operation in Postgres collection.
Also fixes integration tests for Mongo.
Ran the integration tests suite, and verified the behaviour between postgres and mongo.
- [* ] My changes generate no new warnings
- [*] I have added tests that prove my fix is effective or that my feature works
- [*] Any dependent changes have been merged and published in downstream modules
=> feat: Postgres Collection - Implement NEQ filter

document-store/build.gradle.kts
Updating mongo dependency due to https://snyk.io/vuln/SNYK-JAVA-ORGMONGODB-1079241
=> chore: update vulnerable mongo driver

document-store/build.gradle.kts, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/postgres/PostgresDocStoreTest.java
=> test: Use testcontainer for integration test

build.gradle.kts, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/postgres/PostgresDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/utils/Utils.java, document-store/src/main/java/org/hypertrace/core/documentstore/Collection.java, document-store/src/main/java/org/hypertrace/core/documentstore/DatastoreProvider.java, document-store/src/main/java/org/hypertrace/core/documentstore/Document.java, document-store/src/main/java/org/hypertrace/core/documentstore/DocumentStoreConfig.java, document-store/src/main/java/org/hypertrace/core/documentstore/Filter.java, document-store/src/main/java/org/hypertrace/core/documentstore/OrderBy.java, document-store/src/main/java/org/hypertrace/core/documentstore/Query.java, document-store/src/main/java/org/hypertrace/core/documentstore/SingleValueKey.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoDatastore.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/Params.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresDatastore.java, document-store/src/test/java/org/hypertrace/core/documentstore/FilterTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/QueryTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoCollectionTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoDatastoreTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/ParamsTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/PostgresCollectionTest.java
=> chore: added code style plugin

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/postgres/PostgresDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresDatastore.java
Move out all the common test for Postgres & Mongo
=> test: Refactor integration test

document-store/build.gradle.kts, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/postgres/PostgresDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresDatastore.java
=> test: Parametrize integration test

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/postgres/PostgresDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java
Test Cases for getJsonNodeAtPath method
It tests
For a given path, what would be the JSON path
If path is null, what would be the JSON path
If path is empty string, what would be the JSON path
=> Test cases for getJsonNodeAtPath

document-store/src/main/java/org/hypertrace/core/documentstore/Collection.java
Enhance documentation comments for the 'upsert' and 'upsertAndReturn' APIs
No testing required. Only documentation update.
=> Enhance documentation comments for the 'upsert' and 'upsertAndReturn' APIs

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreQueryV1Test.java, document-store/src/integrationTest/resources/query/update_operator/object_updated1.json, document-store/src/integrationTest/resources/query/update_operator/object_updated2.json, document-store/src/main/java/org/hypertrace/core/documentstore/model/subdoc/MultiValuedNestedSubDocumentValue.java, document-store/src/main/java/org/hypertrace/core/documentstore/model/subdoc/SubDocument.java, document-store/src/main/java/org/hypertrace/core/documentstore/model/subdoc/SubDocumentValue.java, document-store/src/main/java/org/hypertrace/core/documentstore/model/subdoc/visitor/SubDocumentValueVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/subdoc/MongoSubDocumentValueParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/subdoc/PostgresSubDocumentArrayGetter.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/subdoc/PostgresSubDocumentValueAddToListIfAbsentParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/subdoc/PostgresSubDocumentValueParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/update/parser/PostgresAddToListIfAbsentParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/update/parser/PostgresRemoveAllFromListParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/utils/PostgresUtils.java
Extending the update operator support for multi-valued subdocuments.
=> Multi-valued subdocument operators implementation

document-store/build.gradle.kts
This PR updates `postgresql` version to fix known vulnerabilities in the existing one.(https://mvnrepository.com/artifact/org.postgresql/postgresql)
=> fix vulnerabilities

document-store/build.gradle.kts
Updates jackson-databind version to fix know vulnerability. (https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind)
=> fix jackson databind vulnerability

document-store/build.gradle.kts
Remove the accidental repo. addition introduced by https://github.com/hypertrace/document-store/pull/152/files#diff-8ca21536445bce7c343741dbe5765907edd0819315aeec43e2e5b5fb268c28f5
=> Remove the repo. addition

document-store/build.gradle.kts, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
Using gradle toml for easy management of dependency versions
=> Using toml in document-store

gradle/libs.versions.toml
=> refactor: restructure toml file for Vulnerability fixes

owasp-suppressions.xml
https://nvd.nist.gov/vuln/detail/CVE-2024-1597
=> chore: suppress vulnerability

gradle/libs.versions.toml, owasp-suppressions.xml
=> chore: update postgresql version to fix vuln

document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java
Reverts hypertrace/document-store#196
Reverting the PR as I am catching and using the duplicate key exception to update
=> Revert "chore: reorder error log and exception"

document-store/src/main/java/org/hypertrace/core/documentstore/metric/BaseDocStoreMetricProviderImpl.java, document-store/src/test/java/org/hypertrace/core/documentstore/metric/BaseDocumentStoreMetricProviderImplTest.java
Added null placeholder value for missing attributes in entities.
=> chore: add null placeholder for missing attributes in custom metric registry

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreQueryV1Test.java, document-store/src/integrationTest/resources/query/update_operator/updated4.json, document-store/src/integrationTest/resources/query/update_operator/updated5.json, document-store/src/main/java/org/hypertrace/core/documentstore/model/options/UpdateOptions.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/update/MongoUpdateExecutor.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoCollectionTest.java
Exposed mongo update options to client, this will help us in subdocUpdateOrUpsert queries.
=> Exposed update option upsert to client
