document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/Collection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java
This PR adds support to atomically upsert and return the result. Existing APIs only support upserting with a boolean status of the result, forcing multiple round trips to retrieve the result. This API was added rather than updating the existing API for backwards compatibility.
This will be used by updates in entity service to streamline the behavior of the entity upsert API.
Integration tests have been added to test the new API.
Javadoc added for the new API
=> feat: add upsert and return support

document-store/build.gradle.kts, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java
See https://jira.mongodb.org/browse/SERVER-47212
The current MongoDB servers we use have a known issue - https://jira.mongodb.org/browse/SERVER-47212
where the findAndModify operation might fail with duplicate key exception and server was supposed to
retry that but it doesn't. Since the fix isn't available in the released MongoDB versions,
we are retrying the upserts in these cases in client layer so that we avoid frequent failures in this layer.
=> fix: Retrying upserts which fails due to a known MongoDB bug.

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/test/java/org/hypertrace/core/documentstore/FilterTest.java
_lastUpdateTime stores the last updated timestamp in Date and has different
convention than createdTime.
field name without underscore is preferred, and long value makes it
easier for comparison with the current type support
=> Makes lastUpdatedTime consistent with createdTime

document-store/build.gradle.kts, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/postgres/PostgresDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/Collection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java
This will help the clients to build more interesting use cases and also cutdown a roundtrip to the server.
A use case where this has even become essential is more like a change data capture kind of use case: A client wants to upsert a bunch of docs but it needs to know what all changed in those docs compared to the previous version of the docs so that it can optimize some processing. CDC (Change data capture) at the doc store level might be helpful but that's much more heavy weight and doesn't have enough use cases currently to bring that in. 
Also, it's a known that the new API is sync API and could take a bit longer than other APIs so it should be used wisely based on the use cases.
=> Adding a new returnAndBulkUpsert API in the doc store.

document-store/src/main/java/org/hypertrace/core/documentstore/Filter.java, document-store/src/main/java/org/hypertrace/core/documentstore/OrderBy.java, document-store/src/main/java/org/hypertrace/core/documentstore/Query.java, document-store/src/test/java/org/hypertrace/core/documentstore/FilterTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/QueryTest.java
Fix equals(), hashcode() and toString() methods. 
equals() method in `Filter` and `Query` was throwing NPE previously for some cases(newly added tests demonstrate that). 
Updated unit tests.
=> Fix equals, hashcode and toString methods

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/postgres/PostgresDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/Collection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/PostgresCollectionTest.java
Add Implementation of EXISTS and NOT_EXISTS operator in postgres.
Addresses the issue https://github.com/hypertrace/document-store/issues/19
- Updated unit tests
- Added integration tests for these filters for both mongo and postgres
=> postgres: Add support for EXISTS and NOT_EXISTS operator

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/postgres/PostgresDocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/utils/Utils.java, document-store/src/main/java/org/hypertrace/core/documentstore/Filter.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoCollectionTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/PostgresCollectionTest.java
Provides an implementation of an issue - https://github.com/hypertrace/document-store/issues/32 - of adding `not_in` filter.
It implements for both mongo + Postgres implementation of document store interface. However, there is some limitation on
postgres side. On Postgres side, it only supports non-array field and highlighted here - https://github.com/hypertrace/document-store/issues/32#issuecomment-781411676
- Adds integration tests for various scenarios
None. will be covered in the release note.
=> feat:adds supports for not_in filter in postgres and mongodb

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java
- adds integration test for `contains` filter for mongo implementation.
- will help in implemeting `contains` on the Postgres side as part of the issue - https://github.com/hypertrace/document-store/issues/19. As part of this issue, `exists` and `not_exists` was taken care - https://github.com/hypertrace/document-store/pull/33
=> chore: adds integration test for contains filter for doc-store query of mongo implementation

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoDocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/BulkUpdateRequest.java, document-store/src/main/java/org/hypertrace/core/documentstore/BulkUpdateResult.java, document-store/src/main/java/org/hypertrace/core/documentstore/Collection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java
Add bulk update API implementation for Mongo. This PR does not provide an implementation for postgresql and can be added in a follow up PR
=> Issue: https://github.com/hypertrace/document-store/issues/48

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoQueryParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresQueryParser.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoCollectionTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoQueryParserTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/PostgresQueryParserTest.java
Fixes https://github.com/hypertrace/document-store/issues/50 by using `LinkedHashMap` instead of `HashMap` for `orderByMap` to preserve the order of keys (as in the list).
Added unit test
=> Fixes #50: Handle sorting of documents on multiple attributes

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java
Fix for the issue - https://github.com/hypertrace/hypertrace/issues/248
As recently, we have added support for time-agnostic API support and the corresponding GraphQL query was failing.
```
{
entities(
type: SERVICE
limit: 1
between: {startTime: "2021-06-01T14:59:41.614Z", endTime: "2021-06-01T15:59:41.614Z"}
filterBy: [{operator: EQUALS, value: "b89ddf9b-c582-3d93-9006-a4b3024cf5a5", type: ID, idType: SERVICE}]
includeInactive: true
) {
results {
id
name: attribute(key: "name")
__typename
}
__typename
}
}
```
As the flag `includeInactive: true` along with attribute data source, triggers different workflow for fetching from the document store ( mongo/postgres) or OLAP store. In the previous release, it was fetched from pinot. But, in the latest release, it is fetched from the document …
=> fix: postgres iterator interface to handle any order

document-store/build.gradle.kts, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoQueryExecutorIntegrationTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/parser/MongoSelectingExpressionParser.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoQueryExecutorTest.java
Handle duplications using
(i) a overwrite strategy for duplicate selections
(ii) an error-out strategy for duplicate aliases
Duplicate selections were causing a problem. This PR is to fix the issue.
Added necessary unit and integration tests
=> Handling duplicate selections in MongoDB

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoQueryExecutorIntegrationTest.java, document-store/src/integrationTest/resources/mongo/aggregate_on_nested_fields_response.json, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoUtils.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/parser/MongoProjectionSelectingExpressionParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/query/transformer/MongoSelectionsAddingTransformation.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoQueryExecutorTest.java
* Encode alias in generated selections for aggregations
* Encode alias for AggregateExpression and FunctionExpression while projecting them
* Modified unit and integration tests to cover the scenario
=> Encode alias so that they can contain special characters like dot

document-store/build.gradle.kts
Update the Postgres driver path to avoid sync failure in dependencies
=> Update the Postgres driver path to avoid sync failure in dependencies

.github/workflows/pr-test.yml
Codecov bash uploader is being deprecated and is currently in the brownout phase. We need to upgrade to the v2 gh action in all repos.
More info: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
=> chore: update codecov gha to v2

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoQueryExecutorIntegrationTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java
Calling hasNext on closed cursor is throwing error. Need to maintain closed state locally.
=> Calling hasNext on closed cursor is throwing error.

document-store/src/main/java/org/hypertrace/core/documentstore/expression/model/Hashable.java, document-store/src/main/java/org/hypertrace/core/documentstore/expression/type/FilterTypeExpression.java, document-store/src/main/java/org/hypertrace/core/documentstore/expression/type/FromTypeExpression.java, document-store/src/main/java/org/hypertrace/core/documentstore/expression/type/GroupTypeExpression.java, document-store/src/main/java/org/hypertrace/core/documentstore/expression/type/SelectTypeExpression.java, document-store/src/main/java/org/hypertrace/core/documentstore/expression/type/SortTypeExpression.java, document-store/src/main/java/org/hypertrace/core/documentstore/query/Query.java
Implement equals() and hashCode() in the Query DTO for equating them
=> Make the Query DTO equatable/hashable

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoQueryExecutorIntegrationTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/Collection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoQueryExecutor.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/clause/MongoCountClauseSupplier.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java
Introduce an API to count aggregations
Added integration tests
=> Implement aggregate count API for MongoCollection

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java, document-store/src/integrationTest/resources/mongo/test_selection_expression_nested_fields_alias_result.json, document-store/src/integrationTest/resources/mongo/test_selection_expression_result.json, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/PostgresQueryParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresConstantExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresDataAccessorIdentifierExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresDefaultSelectTypeExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresFieldIdentifierExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresFunctionExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresIdentifierExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresSelectTypeExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/utils/PostgresUtils.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/query/v1/PostgresQueryParserTest.java
As part of the supporting ticket: https://github.com/hypertrace/document-store/issues/82,  
This is the `third` PR in the series. It takes care of 
- supporting selections (older API always used to return full document)
- adds support for FunctionalType expression
- adds the similar pattern of composing SelectionTypeExpression visitors
- adds different types of Identifier visitor for data accessor, field accessor of JSONB document
- adds basic unit tests for selection
- adds integration test both for `mongo` + `Postgres` for a query involving selection
- handles nested fields scenarios
Note:
There is difference between below two queries:
Q1. `SELECT document->'item' AS item, document->'price' AS price FROM testCollection`
Q2. `SELECT document->'item', document->'price' AS price FROM …
=> feat: add support for selections of new query api

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/mongo/MongoQueryExecutorIntegrationTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/utils/Utils.java, document-store/src/integrationTest/resources/mongo/test_aggr_alias_distinct_count_response.json, document-store/src/integrationTest/resources/mongo/test_nest_field_filter_response.json, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/PostgresQueryParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresAggregationFilterTypeExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresDataAccessorIdentifierExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresFilterTypeExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/utils/PostgresUtils.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/query/v1/PostgresQueryParserTest.java
As part of the supporting ticket: https://github.com/hypertrace/document-store/issues/82,  
This is the `seventh` PR in the series. It takes care of 
- supporting pagination clause
- adds unit test + integration tests
- pl. see the below notes for reverting back to the data accessor pattern `->>` in filter clause
- Restricting `Having` clause for only aggregation (not allowing non-alias field)
Note:
In the previous PR - https://github.com/hypertrace/document-store/pull/96, we have moved to field base accessor `->` in Where clase. However, it has some issues with text-based filters. So, as part of this PR, we are reverting back. 
Below is the example of query that were not working with field accessor (and there is not alternative for now):
```
SELECT document->'item' AS item, …
```
=> feat: add supports for pagination expression for new api

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreQueryV1Test.java, document-store/src/integrationTest/resources/mongo/pg_aggregate_on_nested_fields_response.json, document-store/src/integrationTest/resources/mongo/test_string_aggr_alias_distinct_count_response.json, document-store/src/integrationTest/resources/mongo/test_string_in_filter_aggr_alias_distinct_count_response.json, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresAggregateExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresAggregationFilterTypeExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/utils/PostgresUtils.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/query/v1/PostgresQueryParserTest.java
As part of the supporting ticket: https://github.com/hypertrace/document-store/issues/82,  
This is the follow-up PR. It takes care of,
- fixed all the tests that were marked only for mongo context except one.
-  DISTINCT with Groupby is not supported on postgres impl as of now.
- allows fields accessor along with expression in having clause (aggregation filter)
- rewrite count API using sub-query as discussed here - https://github.com/hypertrace/document-store/pull/106#discussion_r926563000
=> fix: fixed few more mongo specific tests

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/utils/Utils.java, document-store/src/main/java/org/hypertrace/core/documentstore/commons/DocStoreConstants.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/internal/BulkUpdateSubDocsInternalResult.java
Two different impl of doc-store had different ways of handling `createdTime` and `lastUpdatedTime`.
- Mongo: `createdTime` and `lastUpdatedTime` are interested as part of document
- Postgres: Had two outer columns called `created_at` and `updated_at` with column type timestampz.
The above differences was causing issues for exposing attributes pointing to `createdTime`.
e.g see below exception on postgres:
```
Caused by: java.lang.NullPointerException
at org.hypertrace.core.documentstore.postgres.query.v1.vistors.PostgresFieldIdentifierExpressionVisitor.visit(PostgresFieldIdentifierExpressionVisitor.java:32)
at org.hypertrace.core.documentstore.postgres.query.v1.vistors.PostgresSortTypeExpressionVisitor.visit(PostgresSortTypeExpressionVisitor.java:51)
at …
```
=> feat: add supports for createTime and lastUpdatedTime in postgresql

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresQueryParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/utils/PostgresUtils.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/PostgresQueryParserTest.java
Ref : https://github.com/hypertrace/document-store/issues/117
As part of this PR:
- add support for selection clause of order Query API
- support fetching values from the outer column in Postgres
- cleaned up the duplicate code
Tested:
- locally verified, existing tests are working fine
- added unit + integration test for selection clause
- tested with a few additional queries directly
Example:
Doctore Query:
```
Query{selections=[entityId, entityType], filter=_id-EQ-default:testKey1, orderBys=[], offset=null, limit=null}
```
Translated Query:
```
SELECT document->'entityId' AS "entityId",document->'entityType' AS "entityType" 
FROM myTest 
WHERE document->>'_id' = 'default:testKey1'
```
=> feat: add selection support in older api

document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresQueryParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresFilterTypeExpressionVisitor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/utils/PostgresUtils.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/PostgresQueryParserTest.java
Currently, filters only support identifier LHS and constant RHS. We may want to extend it to support functional expression on the LHS. This PR is refactoring the existing code so that the Postgres filter type expression parser could be extended later to support functional expressions.
All the existing unit and integration tests are passing.
No new test case is required because, it is just refactoring.
=> Update Postgres Filter Type Expression Parser to make it extendible to non-identifier type LHS

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreQueryV1Test.java, document-store/src/integrationTest/resources/mongo/test_aggr_with_match_selection_and_groupby.json, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/transformer/PostgresSelectionQueryTransformer.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/query/v1/PostgresQueryParserTest.java
The previous fix - https://github.com/hypertrace/document-store/pull/124 for the issue https://github.com/hypertrace/document-store/issues/123, was handling a very specific case.
As part of this PR,
- it makes it more generic, and make sure that all the groupby clause `identifier` match with selection clause identifiers.
Testing:
- all existing tests are passing
- added new unit + integration test
**Example of handling same in existing mongo impl:**
Before transformation:
```
SELECT DISTINCT_COUNT(`quantity`) AS qty_count, `item`, `price` FROM <implicit_collection> WHERE `price` <= 10 GROUP BY `item`
```
After transformation:
```
SELECT DISTINCT(`quantity`) AS qty_count, `_id.item` AS item, `price`, LENGTH(`qty_count`) AS qty_count FROM <implicit_collection> WHERE `price` <= 10 GROUP BY …
```
=> fix: handle group_by identifier more generically

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreQueryV1Test.java, document-store/src/main/java/org/hypertrace/core/documentstore/expression/operators/AggregationOperator.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/parser/MongoAggregateExpressionParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/query/transformer/MongoSelectionsUpdatingTransformation.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresAggregateExpressionVisitor.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/query/v1/PostgresQueryParserTest.java
This PR renames DISTINCT aggregation operator to  DISTINCT_ARRAY. 
Updated all the unit tests accordingly and verified that all pass.
=> chore: rename DISTINCT aggregation operator as DISTINCT_ARRAY

document-store/src/main/java/org/hypertrace/core/documentstore/expression/operators/AggregationOperator.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/parser/MongoAggregateExpressionParser.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/vistors/PostgresAggregateExpressionVisitor.java
Restores DISTINCT operator(and deprecates it).
=> fix: restore DISTINCT operator

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreQueryV1Test.java, document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreTest.java, document-store/src/integrationTest/resources/query/atomic_update_response_get_new_document.json, document-store/src/integrationTest/resources/query/updatable_collection_data_after_atomic_update_selecting_all_props.json, document-store/src/main/java/org/hypertrace/core/documentstore/Collection.java, document-store/src/main/java/org/hypertrace/core/documentstore/expression/impl/KeyExpression.java, document-store/src/main/java/org/hypertrace/core/documentstore/model/exception/DuplicateDocumentException.java, document-store/src/main/java/org/hypertrace/core/documentstore/model/options/ReturnDocumentType.java, document-store/src/main/java/org/hypertrace/core/documentstore/model/options/UpdateOptions.java, document-store/src/main/java/org/hypertrace/core/documentstore/model/subdoc/SubDocument.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoUtils.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresQueryBuilder.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresQueryExecutor.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/subdoc/PostgresSubDocumentUpdater.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/utils/PostgresUtils.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoCollectionTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/PostgresCollectionTest.java
1. Previously the 'create' method was throwing a general IOException irrespective of whether the failure was due to a duplicate key or other reasons. This PR fixes to throw a DuplicateDocumentException in case the failure is due to unique key violations
2. This PR also introduces update options to return old or new document for update
3. Also, this PR fixes a bug in updating nested fields for Postgres
Added the necessary unit and integration tests
=> Enhance the functionalities of the 'create' and 'update' methods

document-store/build.gradle.kts
Upgarded jackson-databind to eradicate CVE-2022-42004 
ref : https://nvd.nist.gov/vuln/detail/CVE-2022-42004
=> Upgarded jackson-databind to eradicate CVE-2022-42004

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreQueryV1Test.java, document-store/src/integrationTest/resources/query/unwind_preserve_with_regular_filter_first_level.json, document-store/src/integrationTest/resources/query/unwind_preserve_with_regular_filter_second_level.json, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/transformer/PostgresQueryTransformer.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/query/v1/transformer/PostgresUnnestQueryTransformer.java, document-store/src/main/java/org/hypertrace/core/documentstore/query/Query.java, document-store/src/main/java/org/hypertrace/core/documentstore/query/transform/TransformedQueryBuilder.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/query/v1/PostgresQueryParserTest.java
This PR handles the backward compatibility scenarios between two implementations of this interface between Postgres and Mongo.
There is no way of accessing an item of a JSON array without w/o index expression. So, that results in the no match.
As a below example, If we try to access, `sales.city` it will return null as there is no key at `sales`.
```
{ "item":"Soap", "sales":[ { "city":"delhi" } ] }
```
However, as mongo supports -EQ- operator on an array field that behaves as contains internally,
`sales.city-EQ-delhi` is a valid filter expression. Ideally, the client should have expressed contains as `sales-CONTAINS-{"city":"delhi"}`.
To support the above in-compatibility w/o affecting the client, for now,  we are adding a query pre-processor for filter expression that will move any …
=> feat: adds support for pre-processing unnest filter for compatibility

.github/workflows/pr-build.yml, .github/workflows/pr-test.yml, .github/workflows/publish.yml, build.gradle.kts, document-store/build.gradle.kts, owasp-suppressions.xml
Downgrade the slf4j api as that will require all consumers to upgrade their logging runtime or otherwise silently break logging. We should be upgrading in the other direction, all consumers then libs.
While fixing that updated CI and switched to owasp checker
=> chore: downgrade logger, add dep check and upgrade vulns

document-store/src/main/java/org/hypertrace/core/documentstore/model/config/mongo/MongoConnectionConfig.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoCollection.java, document-store/src/main/java/org/hypertrace/core/documentstore/postgres/PostgresCollection.java, document-store/src/test/java/org/hypertrace/core/documentstore/postgres/PostgresCollectionTest.java, gradle/libs.versions.toml
1. Enable read-retries for Mongo
2. Close Mongo connection on exceptions in cursor.hasNext()
3. Close Postgres connections on reaching the end of the result set or an exception occurs
=> MongoDB read path enhancements

.github/workflows/pr-test.yml, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/query/MongoQueryExecutor.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoCollectionTest.java, document-store/src/test/java/org/hypertrace/core/documentstore/mongo/MongoQueryExecutorTest.java
Some of the aggregation queries could fail because of memory limits per aggregation pipeline on MongoDB. To avoid such issue, this PR allows disk usage so that the queries that couldn't fit in the memory limits can leverage the disk usage.
=> Enable disk usage for aggregations on MongoDB

document-store/src/main/java/org/hypertrace/core/documentstore/metric/BaseDocStoreMetricProviderImpl.java
=> fix: correctly get string label value for each jsonNode types

document-store/src/integrationTest/resources/create/document_one.json, document-store/src/integrationTest/resources/create/document_one_response.json, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/MongoUtils.java
Reverts hypertrace/document-store#207
=> Revert "Handled dollar prefixed values for "createOrReplace" Mongo implementation"

document-store/src/integrationTest/java/org/hypertrace/core/documentstore/DocStoreQueryV1Test.java, document-store/src/integrationTest/resources/query/collection_data.json, document-store/src/integrationTest/resources/query/test_last_aggregation_operator.json, document-store/src/main/java/org/hypertrace/core/documentstore/expression/operators/AggregationOperator.java, document-store/src/main/java/org/hypertrace/core/documentstore/mongo/query/parser/MongoAggregateExpressionParser.java
=> EN-51893 | CHORE : Adding Last aggregation operator

document-store/src/main/java/org/hypertrace/core/documentstore/model/subdoc/SubDocument.java
This will allow subdocpath to have "-" in it. It will be used in cases where we want to add negative values to a map to list.
=> added hiphen in subdocpath

document-store/src/main/java/org/hypertrace/core/documentstore/mongo/update/MongoUpdateExecutor.java
=> Add realtime freshness to bulk update query

document-store/src/main/java/org/hypertrace/core/documentstore/mongo/query/MongoQueryExecutor.java
MongoExecutionTimeoutException is of type MongoException
=> Aggregate operation is throwing MongoExecutionTimeoutException

document-store/src/main/java/org/hypertrace/core/documentstore/metric/BaseDocStoreMetricProviderImpl.java
=> chore: add NullNode case while converting values for mertrics reporting
